### ISSUE TITLE
运行amiya.py时报错

### ISSUE THREAD

**Issue by Hurricane35** [vivien8261/Amiya-Bot#13]
求助大佬
PS C:\Files\lzy的bot\amiya\Amiya-Bot> python amiya.py
loading tags data...
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\2\jieba.cache
Loading model cost 1.474 seconds.
Prefix dict has been built successfully.
loading operators data...
loading materials data...
Traceback (most recent call last):
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\amiya.py", line 4, in <module>
    from modules.network.websocketClient import Websocket
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\modules\network\websocketClient.py", line 7, in <module>
    from message.messageHandler import MessageHandler
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\message\messageHandler.py", line 7, in <module>
    from message.replies import reply_func_list
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\message\replies\__init__.py", line 5, in <module>
    from .emotion import emotion
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\message\replies\emotion.py", line 8, in <module>
    amiya_name = database.config.get_amiya_name()
  File "C:\Files\lzy的bot\amiya\Amiya-Bot\database\controller\configController.py", line 16, in get_amiya_name
    self.get_config('amiya_name', 'good_name', True)['config_values'].split(','),
**TypeError: 'NoneType' object is not subscriptable**

**Comment by vivien8261** [comment]
数据库需要导入配置表 [t_config_amiya.sql](https://github.com/vivien8261/Amiya-Bot-resource/blob/master/Database/Data/t_config_amiya.sql)

**Comment by Initial-heart-1** [comment]
@vivien8261 close issue
