### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Nirvana-Chen** [vivien8261/Amiya-Bot#2]
OS: ubuntu 18.04 aliyunserver
python version: 3.7.5
mysql version: 8.0.23 for Linux on x86_64 (MySQL Community Server - GPL)
mirai: 自部署，使用mcl工具独立运行，并安装`mirai-api-http`

已完成资源导入，依赖安装，config也已修改为本机配置，第四步时出现如下问题

```
$ python3 amiya.py
Traceback (most recent call last):
  File "amiya.py", line 8, in <module>
    from message.messageHandler import MessageHandler
  File "/home/nsc-root/Amiya-Bot/message/messageHandler.py", line 10, in <module>
    from message.replies import Replies
  File "/home/nsc-root/Amiya-Bot/message/replies/__init__.py", line 2, in <module>
    from .emotion import emotion
  File "/home/nsc-root/Amiya-Bot/message/replies/emotion.py", line 8, in <module>
    amiya_name = database.config.get_amiya_name()
  File "/home/nsc-root/Amiya-Bot/database/controller/configController.py", line 16, in get_amiya_name
    self.get_config('amiya_name', 'good_name', True)['config_values'].split(','),
TypeError: 'NoneType' object is not subscriptable
```

```
$ python3 quickStart.py Test
Traceback (most recent call last):
  File "quickStart.py", line 3, in <module>
    from message.messageHandler import MessageHandler
  File "/home/nsc-root/Amiya-Bot/message/messageHandler.py", line 10, in <module>
    from message.replies import Replies
  File "/home/nsc-root/Amiya-Bot/message/replies/__init__.py", line 2, in <module>
    from .emotion import emotion
  File "/home/nsc-root/Amiya-Bot/message/replies/emotion.py", line 8, in <module>
    amiya_name = database.config.get_amiya_name()
  File "/home/nsc-root/Amiya-Bot/database/controller/configController.py", line 16, in get_amiya_name
    self.get_config('amiya_name', 'good_name', True)['config_values'].split(','),
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vivien8261** [comment]
现在还需要导入 [基础配置](https://github.com/vivien8261/Amiya-Bot-resource/blob/master/%E6%95%B0%E6%8D%AE%E5%BA%93/config.sql) 的sql文件，原来是读取json文件的，现在改为存到数据库里方便远程修改

**Comment by Nirvana-Chen** [comment]
这部分内容也正确导入到mysql了

**Comment by vivien8261** [comment]
目前看来就是mysql查询不到数据产生的，尝试一下自己执行sql
```sql
select * from t_config_amiya where config_name = "amiya_name" AND config_keyword = "good_name"
```

**Comment by Nirvana-Chen** [comment]
找到问题了，我把三个分别导入到对应名字的database了，于是现在遇到了新的问题
```
$ python3 amiya.py 
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.013 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "amiya.py", line 46, in <module>
    start()
  File "amiya.py", line 18, in start
    http.init_session()
  File "/home/nsc-root/Amiya-Bot/modules/network/httpRequests.py", line 38, in init_session
    session = response['session']
KeyError: 'session'
```

**Comment by Nirvana-Chen** [comment]
已找到问题，需要修改`Amiya-Bot/modules/network/httpRequests.py`第37行中authKey与mirai-api-http中配置的authKey一致，不然无法通过websocket验证。

**Comment by Nirvana-Chen** [comment]
对项目的一点建议：
希望能将authKey通过根目录的配置文件进行读取，避免不同的mirai初始化配置不同带来的问题
另，希望在资源部分说明config.sql和data.sql应该导入amiya数据库
