### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Goodjooy** [vivien8261/Amiya-Bot#7]
运行 `python amiya.py`时报错，
```
Traceback (most recent call last):
  File "amiya.py", line 6, in <module>
    from message.messageHandler import MessageHandler
  File "H:\Amiya-Bot\message\messageHandler.py", line 7, in <module>
    from message.replies import reply_func_list
  File "H:\Amiya-Bot\message\replies\__init__.py", line 5, in <module>
    from .emotion import emotion
  File "H:\Amiya-Bot\message\replies\emotion.py", line 8, in <module>
    amiya_name = database.config.get_amiya_name()
  File "H:\Amiya-Bot\database\controller\configController.py", line 16, in get_amiya_name
    self.get_config('amiya_name', 'good_name', True)['config_values'].split(','),
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Goodjooy** [comment]
导入完整数据问题即解决
